modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mixins]]
config="cbc_cryo_cannon.mixins.json"

[[mods]]
modId="cbc_cryo_cannon"
version="${file.jarVersion}"
displayName="CBC Cryo-Cannon"
authors="Rhuloe"
description='''
Cryogenic ammunition and logistics for Create Big Cannons.
'''

[[dependencies.cbc_cryo_cannon]]
modId="neoforge"
type="required"
versionRange="[21.1.233,)"
ordering="NONE"
side="BOTH"

[[dependencies.cbc_cryo_cannon]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.cbc_cryo_cannon]]
modId="create"
type="required"
versionRange="[6.0.10,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cbc_cryo_cannon]]
modId="createbigcannons"
type="required"
versionRange="[5.11.7,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cbc_cryo_cannon]]
modId="ritchiesprojectilelib"
type="required"
versionRange="[2.1.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cbc_cryo_cannon]]
modId="spore"
type="required"
versionRange="[2.2.0j,)"
ordering="AFTER"
side="BOTH"